// <auto-generated />
using System;
using ComicShelf.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComicShelf.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190303191133_PiotrWasWrongAndNowFixedDb")]
    partial class PiotrWasWrongAndNowFixedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComicShelf.DataAccess.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("IsPublic");

                    b.Property<bool>("IsWantList");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("ComicShelf.DataAccess.Entities.Comic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CollectionId");

                    b.Property<string>("Cover");

                    b.Property<string>("Draftsman");

                    b.Property<byte[]>("Image");

                    b.Property<int>("Issue");

                    b.Property<string>("Note");

                    b.Property<DateTime>("PremierDate");

                    b.Property<string>("Publisher");

                    b.Property<string>("ScriptWriter");

                    b.Property<string>("Series");

                    b.Property<string>("Title");

                    b.Property<string>("Translator");

                    b.Property<int>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Comics");
                });

            modelBuilder.Entity("ComicShelf.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("GivenName");

                    b.Property<string>("GoogleId");

                    b.Property<string>("Name");

                    b.Property<string>("Picture");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComicShelf.DataAccess.Entities.Collection", b =>
                {
                    b.HasOne("ComicShelf.DataAccess.Entities.User")
                        .WithMany("ComicsCollections")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ComicShelf.DataAccess.Entities.Comic", b =>
                {
                    b.HasOne("ComicShelf.DataAccess.Entities.Collection")
                        .WithMany("Comics")
                        .HasForeignKey("CollectionId");
                });
#pragma warning restore 612, 618
        }
    }
}
